## Basics

Tensors = multi-dimensional arrays(ordered arrangement of numbers). 

single number = 0-D. for eg: 9. this has no shape
1 row of numbers or several 0-D tensor = 1-D for eg: [1,2,4]. this has shape (4,)

made of several 1-D tensor = 2-D for: [[2, 4, 3],
                                      [5, 6, 7]]
this has shape (2,3)

combine several 2-D tensor= 3-D tensor. for eg:[[[2, 4, 3],
                                                [5, 6, 7]],
                                                [[2, 4, 3],
                                                [5, 6, 7]]]
This has shape (2,2,3)

In [1]:
import tensorflow as tf
tensor_zero=tf.constant(4)
print(tensor_zero)

tf.Tensor(4, shape=(), dtype=int32)


In [2]:
tensor_one=tf.constant([4,2])
print(tensor_one)

tf.Tensor([4 2], shape=(2,), dtype=int32)


In [3]:
tensor_two=tf.constant([[4,2],[3,5]])
print(tensor_two)

tf.Tensor(
[[4 2]
 [3 5]], shape=(2, 2), dtype=int32)


In [4]:
tensor_three=tf.constant([[[4,2]],[[3,5]]])
print(tensor_three)

tf.Tensor(
[[[4 2]]

 [[3 5]]], shape=(2, 1, 2), dtype=int32)


In [2]:
tensor_float= tf.constant([2,0.,-3,8], dtype=tf.float32)
casted_tensor_int = tf.cast(tensor_float, dtype=tf.int16) # tf.cast change datatype
print(tensor_float)
print(casted_tensor_int)

tf.Tensor([ 2.  0. -3.  8.], shape=(4,), dtype=float32)
tf.Tensor([ 2  0 -3  8], shape=(4,), dtype=int16)


In [3]:
# convert numpy array to tensor
import numpy as np
np_array = np.array([1,2,3])
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [5]:
#eye method = construct an identity matrix or a batch of matrices
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=4,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]], shape=(3, 4), dtype=float32)


In [7]:
#fill method= create a tensor filled with a scalar value
#tf.fill(dims, value, name=None)

fill_tensor =tf.fill(
    [3,4],5, name=None
)

print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [8]:
#ones method= creates a tensor with all elements set to one
#tf.ones(shape, dtype= tf.dtypes.float32, namee=None)
one_tensor = tf.ones(
    [5,3],
    dtype=tf.dtypes.float32,
    name=None
)

print(one_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [10]:
#ones_like method= create a tensor of all ones that has the same shape as the input
#tf.ones_like(input, dtype=None, name=None)
ones_like_tensor=tf.ones_like(fill_tensor)
print(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)


In [3]:
# zeros = create a tensor with all elements set to zero
zero_tensor= tf.zeros(
    [5,3],
    dtype=tf.dtypes.float32,
    name=None
)

print(zero_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [14]:
#shape = returns a tensoe conatining the shape of the input tensor
shape_tensor = tf.shape(
    zero_tensor,
    out_type=tf.int32
)
print(shape_tensor)

tf.Tensor([5 3], shape=(2,), dtype=int32)


In [16]:
size_tensor= tf.size(
    zero_tensor,
    out_type=tf.float32
)
print(size_tensor)

tf.Tensor(15.0, shape=(), dtype=float32)


In [ ]:
#random.normal = outputs random values from a normal distribution
random_tensor = tf.random.normal(
    shape=[3,2],
    mean=1111.0,
    stddev=2221.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 4621.3506   2729.938  ]
 [ 2333.6624   2705.2656 ]
 [-1687.2905    170.59027]], shape=(3, 2), dtype=float32)


In [31]:
#random.uniform=output randoms value from uniform distribution
random_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=1,
    dtype=tf.dtypes.float32,
    seed=4,
    name=None
)
print(random_tensor)

tf.Tensor([0.721082   0.16421127 0.0344758  0.6312306  0.05017233], shape=(5,), dtype=float32)


In [ ]:
#set_seed = produce same values
tf.random.set_seed(5)
random_tensor1=tf.random.uniform(shape=[2,3],maxval=3, dtype=tf.int32,seed=10)
tf.random.set_seed(5)
random_tensor2=tf.random.uniform(shape=[2,3],maxval=3, dtype=tf.int32,seed=10)
print(random_tensor1)
print(random_tensor2)

tf.Tensor(
[[2 0 1]
 [2 1 1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[2 0 1]
 [2 1 1]], shape=(2, 3), dtype=int32)


## Index

In [37]:
tensor_indexed =  tf.constant([3,6,2,4,6])
print(tensor_indexed)
print(tensor_indexed[0:3])
print(tensor_indexed[0:5:2])# from 0 to 5 with 2 step

tf.Tensor([3 6 2 4 6], shape=(5,), dtype=int32)
tf.Tensor([3 6 2], shape=(3,), dtype=int32)
tf.Tensor([3 2 6], shape=(3,), dtype=int32)


In [44]:
tensor_two_indexed = tf.constant([[1,2,3],
                                 [3,5,6]])
print(tensor_two_indexed[0:2,0:1])
print(tensor_two_indexed[1,1])
print(tensor_two_indexed[..., 1]) # all element of col 1 index

tf.Tensor(
[[1]
 [3]], shape=(2, 1), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([2 5], shape=(2,), dtype=int32)


## Maths Operations

In [ ]:
#math.abs= computes value of a tensor to absloute value
abs_value = tf.constant([-2.25,3.25])
tf.abs(abs_value)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [5]:
# for complex 
abs_value_complex =tf.constant([-4.1+6.1j])
print(tf.abs(abs_value_complex))
print(tf.sqrt((-4.1)**2 + 6.1**2))


tf.Tensor([7.34982993], shape=(1,), dtype=float64)
tf.Tensor(7.34983, shape=(), dtype=float32)


In [ ]:
x_1 =tf.constant([1,2,3,4,5], dtype=tf.int32)
x_2 =tf.constant([1,2,3,4,5], dtype=tf.int32)
print(tf.multiply(x_1,x_2))
print(tf.divide(x_1,x_2))
#divide_no_nan = commputes a safe divide which returns 0 if y (denominator) is zero
x_3= tf.constant([0,2,3,0,5], dtype=tf.int32)
print(tf.divide(x_1,x_3))# it shows inf(infinite) where divided by zero
print(tf.math.divide_no_nan(x_1,x_3)) # it will show 0

tf.Tensor([ 1  4  9 16 25], shape=(5,), dtype=int32)
tf.Tensor([1. 1. 1. 1. 1.], shape=(5,), dtype=float64)
tf.Tensor([inf  1.  1. inf  1.], shape=(5,), dtype=float64)
tf.Tensor([0. 1. 1. 0. 1.], shape=(5,), dtype=float64)


In [17]:
# each will be added by the value  of y
x =tf.constant([1,2,3,4,5], dtype=tf.int32)
y =tf.constant([1], dtype=tf.int32) # we are doing stretch of x by 1
y_1 =tf.constant([1,1,1,1,1], dtype=tf.int32)
print(tf.math.add(x,y))
print(tf.add(x,y_1))

tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)
tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)


In [15]:
x1= tf.constant([[1,2,3,4,5,6],], dtype=tf.float32)
x2= tf.constant([[2],[1],[10]], dtype=tf.float32)
print(tf.math.multiply(x1,x2))

tf.Tensor(
[[ 2.  4.  6.  8. 10. 12.]
 [ 1.  2.  3.  4.  5.  6.]
 [10. 20. 30. 40. 50. 60.]], shape=(3, 6), dtype=float32)


In [19]:
# maximum = returns the max of x and y (i.e. x>y ? x:y) element-wise
x4 =tf.constant([1,2,3,4,5], dtype=tf.int32)
x5 =tf.constant([1,2,3,0,5], dtype=tf.int32)
print(tf.math.minimum(x4,x5))

tf.Tensor([1 2 3 0 5], shape=(5,), dtype=int32)


In [20]:
# argmax= returns the index with the largest value across axes of a tensor
print(tf.math.argmax(x4))
print(tf.math.argmin(x5))

tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)


In [23]:
x = tf.constant([[1,4,20],
                 [3,8,6]])
print(tf.math.argmax(x, axis=1))
print(tf.math.argmax(x, axis=0))

tf.Tensor([2 1], shape=(2,), dtype=int64)
tf.Tensor([1 1 0], shape=(3,), dtype=int64)


In [24]:
x=tf.constant([[1,2],[3,4]])
y=tf.constant([[2,0],[1,2]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  1],
       [ 3, 16]], dtype=int32)>

In [ ]:
#reduce_sum = commputes the sum of elements across dimensions of a tensor
print(tf.math.reduce_sum(y,axis=None, keepdims=False, name=None))
print(tf.math.reduce_max(y,axis=None, keepdims=False, name=None))
print(tf.math.reduce_sum(y,axis=0, keepdims=False, name=None)) # axis= 0 column

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([3 2], shape=(2,), dtype=int32)


In [ ]:
#sigmoid = sigmoid(x)=y= 1/(1+exp(-x)) for xE (-inf,inf), sigmoid(x)E(0,1)
x = tf.constant([[1, 2, 3],  
                 [3, 5, 6]], dtype=tf.float32)
tf.math.sigmoid(x)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.7310586 , 0.8807971 , 0.95257413],
       [0.95257413, 0.9933072 , 0.99752736]], dtype=float32)>

In [34]:
# top_k = find values and indices of the k largest entries for the last dimension
x0 = tf.constant([[1, 12, 3],  
                 [13, 5, 6]], dtype=tf.float32)
tf.math.top_k(
    x0, k=2, sorted=True, name=None
)

TopKV2(values=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[12.,  3.],
       [13.,  6.]], dtype=float32)>, indices=<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [0, 2]], dtype=int32)>)

## Linear ALgebra Operation