## Basics

Tensors = multi-dimensional arrays(ordered arrangement of numbers). 

single number = 0-D. for eg: 9. this has no shape
1 row of numbers or several 0-D tensor = 1-D for eg: [1,2,4]. this has shape (4,)

made of several 1-D tensor = 2-D for: [[2, 4, 3],
                                      [5, 6, 7]]
this has shape (2,3)

combine several 2-D tensor= 3-D tensor. for eg:[[[2, 4, 3],
                                                [5, 6, 7]],
                                                [[2, 4, 3],
                                                [5, 6, 7]]]
This has shape (2,2,3)

In [1]:
import tensorflow as tf
tensor_zero=tf.constant(4)
print(tensor_zero)

tf.Tensor(4, shape=(), dtype=int32)


In [2]:
tensor_one=tf.constant([4,2])
print(tensor_one)

tf.Tensor([4 2], shape=(2,), dtype=int32)


In [3]:
tensor_two=tf.constant([[4,2],[3,5]])
print(tensor_two)

tf.Tensor(
[[4 2]
 [3 5]], shape=(2, 2), dtype=int32)


In [4]:
tensor_three=tf.constant([[[4,2]],[[3,5]]])
print(tensor_three)

tf.Tensor(
[[[4 2]]

 [[3 5]]], shape=(2, 1, 2), dtype=int32)


In [2]:
tensor_float= tf.constant([2,0.,-3,8], dtype=tf.float32)
casted_tensor_int = tf.cast(tensor_float, dtype=tf.int16) # tf.cast change datatype
print(tensor_float)
print(casted_tensor_int)

tf.Tensor([ 2.  0. -3.  8.], shape=(4,), dtype=float32)
tf.Tensor([ 2  0 -3  8], shape=(4,), dtype=int16)


In [3]:
# convert numpy array to tensor
import numpy as np
np_array = np.array([1,2,3])
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [5]:
#eye method = construct an identity matrix or a batch of matrices
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=4,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]], shape=(3, 4), dtype=float32)


In [7]:
#fill method= create a tensor filled with a scalar value
#tf.fill(dims, value, name=None)

fill_tensor =tf.fill(
    [3,4],5, name=None
)

print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [8]:
#ones method= creates a tensor with all elements set to one
#tf.ones(shape, dtype= tf.dtypes.float32, namee=None)
one_tensor = tf.ones(
    [5,3],
    dtype=tf.dtypes.float32,
    name=None
)

print(one_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [10]:
#ones_like method= create a tensor of all ones that has the same shape as the input
#tf.ones_like(input, dtype=None, name=None)
ones_like_tensor=tf.ones_like(fill_tensor)
print(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)


In [3]:
# zeros = create a tensor with all elements set to zero
zero_tensor= tf.zeros(
    [5,3],
    dtype=tf.dtypes.float32,
    name=None
)

print(zero_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [14]:
#shape = returns a tensoe conatining the shape of the input tensor
shape_tensor = tf.shape(
    zero_tensor,
    out_type=tf.int32
)
print(shape_tensor)

tf.Tensor([5 3], shape=(2,), dtype=int32)


In [16]:
size_tensor= tf.size(
    zero_tensor,
    out_type=tf.float32
)
print(size_tensor)

tf.Tensor(15.0, shape=(), dtype=float32)


In [ ]:
#random.normal = outputs random values from a normal distribution
random_tensor = tf.random.normal(
    shape=[3,2],
    mean=1111.0,
    stddev=2221.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 4621.3506   2729.938  ]
 [ 2333.6624   2705.2656 ]
 [-1687.2905    170.59027]], shape=(3, 2), dtype=float32)


In [31]:
#random.uniform=output randoms value from uniform distribution
random_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=1,
    dtype=tf.dtypes.float32,
    seed=4,
    name=None
)
print(random_tensor)

tf.Tensor([0.721082   0.16421127 0.0344758  0.6312306  0.05017233], shape=(5,), dtype=float32)


In [ ]:
#set_seed = produce same values
tf.random.set_seed(5)
random_tensor1=tf.random.uniform(shape=[2,3],maxval=3, dtype=tf.int32,seed=10)
tf.random.set_seed(5)
random_tensor2=tf.random.uniform(shape=[2,3],maxval=3, dtype=tf.int32,seed=10)
print(random_tensor1)
print(random_tensor2)

tf.Tensor(
[[2 0 1]
 [2 1 1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[2 0 1]
 [2 1 1]], shape=(2, 3), dtype=int32)


## Index

In [37]:
tensor_indexed =  tf.constant([3,6,2,4,6])
print(tensor_indexed)
print(tensor_indexed[0:3])
print(tensor_indexed[0:5:2])# from 0 to 5 with 2 step

tf.Tensor([3 6 2 4 6], shape=(5,), dtype=int32)
tf.Tensor([3 6 2], shape=(3,), dtype=int32)
tf.Tensor([3 2 6], shape=(3,), dtype=int32)


In [44]:
tensor_two_indexed = tf.constant([[1,2,3],
                                 [3,5,6]])
print(tensor_two_indexed[0:2,0:1])
print(tensor_two_indexed[1,1])
print(tensor_two_indexed[..., 1]) # all element of col 1 index

tf.Tensor(
[[1]
 [3]], shape=(2, 1), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([2 5], shape=(2,), dtype=int32)


## Maths Operations

In [ ]:
#math.abs= computes value of a tensor to absloute value
abs_value = tf.constant([-2.25,3.25])
tf.abs(abs_value)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [5]:
# for complex 
abs_value_complex =tf.constant([-4.1+6.1j])
print(tf.abs(abs_value_complex))
print(tf.sqrt((-4.1)**2 + 6.1**2))


tf.Tensor([7.34982993], shape=(1,), dtype=float64)
tf.Tensor(7.34983, shape=(), dtype=float32)


In [ ]:
x_1 =tf.constant([1,2,3,4,5], dtype=tf.int32)
x_2 =tf.constant([1,2,3,4,5], dtype=tf.int32)
print(tf.multiply(x_1,x_2))
print(tf.divide(x_1,x_2))
#divide_no_nan = commputes a safe divide which returns 0 if y (denominator) is zero
x_3= tf.constant([0,2,3,0,5], dtype=tf.int32)
print(tf.divide(x_1,x_3))# it shows inf(infinite) where divided by zero
print(tf.math.divide_no_nan(x_1,x_3)) # it will show 0

tf.Tensor([ 1  4  9 16 25], shape=(5,), dtype=int32)
tf.Tensor([1. 1. 1. 1. 1.], shape=(5,), dtype=float64)
tf.Tensor([inf  1.  1. inf  1.], shape=(5,), dtype=float64)
tf.Tensor([0. 1. 1. 0. 1.], shape=(5,), dtype=float64)


In [17]:
# each will be added by the value  of y
x =tf.constant([1,2,3,4,5], dtype=tf.int32)
y =tf.constant([1], dtype=tf.int32) # we are doing stretch of x by 1
y_1 =tf.constant([1,1,1,1,1], dtype=tf.int32)
print(tf.math.add(x,y))
print(tf.add(x,y_1))

tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)
tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)


In [15]:
x1= tf.constant([[1,2,3,4,5,6],], dtype=tf.float32)
x2= tf.constant([[2],[1],[10]], dtype=tf.float32)
print(tf.math.multiply(x1,x2))

tf.Tensor(
[[ 2.  4.  6.  8. 10. 12.]
 [ 1.  2.  3.  4.  5.  6.]
 [10. 20. 30. 40. 50. 60.]], shape=(3, 6), dtype=float32)


In [19]:
# maximum = returns the max of x and y (i.e. x>y ? x:y) element-wise
x4 =tf.constant([1,2,3,4,5], dtype=tf.int32)
x5 =tf.constant([1,2,3,0,5], dtype=tf.int32)
print(tf.math.minimum(x4,x5))

tf.Tensor([1 2 3 0 5], shape=(5,), dtype=int32)


In [20]:
# argmax= returns the index with the largest value across axes of a tensor
print(tf.math.argmax(x4))
print(tf.math.argmin(x5))

tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)


In [23]:
x = tf.constant([[1,4,20],
                 [3,8,6]])
print(tf.math.argmax(x, axis=1))
print(tf.math.argmax(x, axis=0))

tf.Tensor([2 1], shape=(2,), dtype=int64)
tf.Tensor([1 1 0], shape=(3,), dtype=int64)


In [24]:
x=tf.constant([[1,2],[3,4]])
y=tf.constant([[2,0],[1,2]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  1],
       [ 3, 16]], dtype=int32)>

In [ ]:
#reduce_sum = commputes the sum of elements across dimensions of a tensor
print(tf.math.reduce_sum(y,axis=None, keepdims=False, name=None))
print(tf.math.reduce_max(y,axis=None, keepdims=False, name=None))
print(tf.math.reduce_sum(y,axis=0, keepdims=False, name=None)) # axis= 0 column

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([3 2], shape=(2,), dtype=int32)


In [ ]:
#sigmoid = sigmoid(x)=y= 1/(1+exp(-x)) for xE (-inf,inf), sigmoid(x)E(0,1)
x = tf.constant([[1, 2, 3],  
                 [3, 5, 6]], dtype=tf.float32)
tf.math.sigmoid(x)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.7310586 , 0.8807971 , 0.95257413],
       [0.95257413, 0.9933072 , 0.99752736]], dtype=float32)>

In [34]:
# top_k = find values and indices of the k largest entries for the last dimension
x0 = tf.constant([[1, 12, 3],  
                 [13, 5, 6]], dtype=tf.float32)
tf.math.top_k(
    x0, k=2, sorted=True, name=None
)

TopKV2(values=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[12.,  3.],
       [13.,  6.]], dtype=float32)>, indices=<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [0, 2]], dtype=int32)>)

## Linear ALgebra Operation

In [3]:
#matmul = multiplies matrix a by b producing a*b
import tensorflow as tf 
a=[[1,2],[3,4]]
b=[[1,2],[2,3]]
tf.linalg.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  8],
       [11, 18]], dtype=int32)>

In [6]:
tf.transpose(a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

In [7]:
tf.linalg.matmul(a, b, transpose_a=True, transpose_b=True) # transpose value of a and b 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 11],
       [10, 16]], dtype=int32)>

In [21]:
a=[[1,2,3],
   [5,6,7],
   [8,9,1],
   [8,8,3],
   [1,4,6]]
tf.linalg.band_part(a, -1, 0)


<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [5, 6, 0],
       [8, 9, 1],
       [8, 8, 3],
       [1, 4, 6]], dtype=int32)>

In [22]:
tf.linalg.band_part(a, num_lower=1,num_upper=0)

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [5, 6, 0],
       [0, 9, 1],
       [0, 0, 3],
       [0, 0, 0]], dtype=int32)>

In [23]:
tf.linalg.band_part(a, num_lower=0,num_upper=1)

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[1, 2, 0],
       [0, 6, 7],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [41]:
# m = row and n=col 
# m-n<= lower and n-m<==upper
tf.linalg.band_part(a, num_lower=0,num_upper=1)

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[1, 2, 0],
       [0, 6, 7],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [ ]:
#inv =inverse
import tensorflow as tf

a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
inv_a = tf.linalg.inv(a)

print(inv_a)

tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)


In [4]:
a = tf.constant([[1.0, 2.0], [3.0, 4.0]], dtype=tf.float32)  # Ensure float type
s, u, v = tf.linalg.svd(a)

print("Singular values:", s)
print("Left singular vectors (U):", u)
print("Right singular vectors (V):", v)

Singular values: tf.Tensor([5.4649854  0.36596614], shape=(2,), dtype=float32)
Left singular vectors (U): tf.Tensor(
[[ 0.4045535 -0.9145143]
 [ 0.9145143  0.4045535]], shape=(2, 2), dtype=float32)
Right singular vectors (V): tf.Tensor(
[[ 0.5760484  0.8174156]
 [ 0.8174156 -0.5760484]], shape=(2, 2), dtype=float32)


In [7]:
#einsum
A = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
B = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)
# ij is of A and jk is of B this is row column. This give ik shape  
C = tf.einsum('ij,jk->ik', A, B)  # Equivalent to tf.matmul(A, B) 
print(C)

A_T = tf.einsum('ij->ji', A)  # Equivalent to tf.transpose(A)
print(A_T)


tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 3.]
 [2. 4.]], shape=(2, 2), dtype=float32)


In [ ]:
import numpy as np
A = np.array( [[[1,3,4,],
                [3,24,5,]],
               [[1,3,4,],
                [3,24,5,]]])
B = np.array( [[[1,3,4,],
                [3,24,5,],
                [3,24,5,]],
               [[1,3,4,],
                [3,24,5,],
                [3,24,5,]]])
print("Batch multi C=")
print(np.matmul(A,B),"\n")

# Convert NumPy arrays to TensorFlow tensors
A_tf = tf.convert_to_tensor(A, dtype=tf.float32)
B_tf = tf.convert_to_tensor(B, dtype=tf.float32)

print("Einsum C =")
print(tf.einsum('bij,bjk->bik',A_tf,B_tf))

Batch multi C=
[[[ 22 171  39]
  [ 90 705 157]]

 [[ 22 171  39]
  [ 90 705 157]]] 

Einsum C =
tf.Tensor(
[[[ 22. 171.  39.]
  [ 90. 705. 157.]]

 [[ 22. 171.  39.]
  [ 90. 705. 157.]]], shape=(2, 2, 3), dtype=float32)


In [36]:
D = np.array( [[[1,3,4,],
                [3,24,5,]],
               [[1,3,4,],
                [3,24,5,]]])
E = np.array( [[[1,3,4,],
                [3,24,5,]],
               [[1,3,4,],
                [3,24,5,]]])
# Convert NumPy arrays to TensorFlow tensors
D_tf = tf.convert_to_tensor(D, dtype=tf.float32) #bqm where b is batch, q is row and m is column
E_tf = tf.convert_to_tensor(E, dtype=tf.float32) #bqm 

# if we do multiplcation then D_tf col must be equal to row of E_tf 
# since they are mot equal we transpose E_tf then bmq 
# now D_tf = bqm and E_tf transpose = bmq this means D_tf col and E_tf transpose row is equal
# this give bqq 
# Transpose E_tf to (b, m, q)
E_tf_T = tf.transpose(E_tf, perm=[0, 2, 1])


# Perform einsum (b, q, m) @ (b, m, q) -> (b, q, q)
F_tf = tf.einsum('bqm,bme->bqe', D_tf, E_tf_T)

print("Einsum F =")
print(F_tf, "\n")

print("Batch multi H=")
print(np.matmul(D_tf, E_tf_T),"\n")

# transpose with in it
G_tf = tf.einsum('bqm,bem->bqe', D_tf, E_tf)
print(G_tf)

Einsum F =
tf.Tensor(
[[[ 26.  95.]
  [ 95. 610.]]

 [[ 26.  95.]
  [ 95. 610.]]], shape=(2, 2, 2), dtype=float32) 

Batch multi H=
[[[ 26.  95.]
  [ 95. 610.]]

 [[ 26.  95.]
  [ 95. 610.]]] 

tf.Tensor(
[[[ 26.  95.]
  [ 95. 610.]]

 [[ 26.  95.]
  [ 95. 610.]]], shape=(2, 2, 2), dtype=float32)


In [39]:
Q= np.random.randn(2,4,6,4,2) #bcij 4-D
K= np.random.randn(2,4,6,4,1) #bcik 4-D


print(np.einsum("bcdik, bcdij -> bcdkj", K,Q).shape)
print(Q.shape)
print(K.shape)


(2, 4, 6, 1, 2)
(2, 4, 6, 4, 2)
(2, 4, 6, 4, 1)


## Tensorflow functions

In [45]:
# expands_dims= returns a tensor with a length 1 axis inserted at index axis
D = tf.constant( [[[1,3,4,],
                [3,24,5,]],
               [[1,3,4,],
                [3,24,5,]]])
print(D.shape)
print(tf.expand_dims(D, axis=1))
print(tf.expand_dims(D, axis=0))
print(tf.expand_dims(D, axis=2))

(2, 2, 3)
tf.Tensor(
[[[[ 1  3  4]
   [ 3 24  5]]]


 [[[ 1  3  4]
   [ 3 24  5]]]], shape=(2, 1, 2, 3), dtype=int32)
tf.Tensor(
[[[[ 1  3  4]
   [ 3 24  5]]

  [[ 1  3  4]
   [ 3 24  5]]]], shape=(1, 2, 2, 3), dtype=int32)
tf.Tensor(
[[[[ 1  3  4]]

  [[ 3 24  5]]]


 [[[ 1  3  4]]

  [[ 3 24  5]]]], shape=(2, 2, 1, 3), dtype=int32)


In [50]:
# squeeze= remove dimension of size 1 from the shape of a tensor
x_D=tf.expand_dims(D, axis=1)
print(x_D)
print(tf.squeeze(x_D,axis=1))

tf.Tensor(
[[[[ 1  3  4]
   [ 3 24  5]]]


 [[[ 1  3  4]
   [ 3 24  5]]]], shape=(2, 1, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  3  4]
  [ 3 24  5]]

 [[ 1  3  4]
  [ 3 24  5]]], shape=(2, 2, 3), dtype=int32)


In [54]:
# reshape
print(tf.reshape(x_D, [2,2,3]))
print(tf.reshape(x_D, [2,6]))
print(tf.reshape(x_D, [12]))
print(tf.reshape(x_D, [1,2,2,3]))

tf.Tensor(
[[[ 1  3  4]
  [ 3 24  5]]

 [[ 1  3  4]
  [ 3 24  5]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[ 1  3  4  3 24  5]
 [ 1  3  4  3 24  5]], shape=(2, 6), dtype=int32)
tf.Tensor([ 1  3  4  3 24  5  1  3  4  3 24  5], shape=(12,), dtype=int32)
tf.Tensor(
[[[[ 1  3  4]
   [ 3 24  5]]

  [[ 1  3  4]
   [ 3 24  5]]]], shape=(1, 2, 2, 3), dtype=int32)


In [ ]:
#concat= cancatenates tensors along one dimension
print(D)
print(tf.concat([D,D],0))
print(tf.concat([D,D],1))


tf.Tensor(
[[[ 1  3  4]
  [ 3 24  5]]

 [[ 1  3  4]
  [ 3 24  5]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  3  4]
  [ 3 24  5]]

 [[ 1  3  4]
  [ 3 24  5]]

 [[ 1  3  4]
  [ 3 24  5]]

 [[ 1  3  4]
  [ 3 24  5]]], shape=(4, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  3  4]
  [ 3 24  5]
  [ 1  3  4]
  [ 3 24  5]]

 [[ 1  3  4]
  [ 3 24  5]
  [ 1  3  4]
  [ 3 24  5]]], shape=(2, 4, 3), dtype=int32)


In [66]:
print(tf.stack([D,D],1))
print(tf.stack([D,D],3))

tf.Tensor(
[[[[ 1  3  4]
   [ 3 24  5]]

  [[ 1  3  4]
   [ 3 24  5]]]


 [[[ 1  3  4]
   [ 3 24  5]]

  [[ 1  3  4]
   [ 3 24  5]]]], shape=(2, 2, 2, 3), dtype=int32)
tf.Tensor(
[[[[ 1  1]
   [ 3  3]
   [ 4  4]]

  [[ 3  3]
   [24 24]
   [ 5  5]]]


 [[[ 1  1]
   [ 3  3]
   [ 4  4]]

  [[ 3  3]
   [24 24]
   [ 5  5]]]], shape=(2, 2, 3, 2), dtype=int32)


In [71]:
print(tf.stack([D,D],3))
tf.concat([tf.expand_dims(D, axis=3) for t in [D,D]],axis=3)

tf.Tensor(
[[[[ 1  1]
   [ 3  3]
   [ 4  4]]

  [[ 3  3]
   [24 24]
   [ 5  5]]]


 [[[ 1  1]
   [ 3  3]
   [ 4  4]]

  [[ 3  3]
   [24 24]
   [ 5  5]]]], shape=(2, 2, 3, 2), dtype=int32)


<tf.Tensor: shape=(2, 2, 3, 2), dtype=int32, numpy=
array([[[[ 1,  1],
         [ 3,  3],
         [ 4,  4]],

        [[ 3,  3],
         [24, 24],
         [ 5,  5]]],


       [[[ 1,  1],
         [ 3,  3],
         [ 4,  4]],

        [[ 3,  3],
         [24, 24],
         [ 5,  5]]]], dtype=int32)>

In [75]:
#pad = pads a tensor
#tf.pad(tensor, paddings, mode="CONSTANT", constant_values=0, name=None)
paddings = tf.constant([[1,1],[2,2],[3,3]])
tf.pad(D, paddings, "CONSTANT", constant_values=99)

<tf.Tensor: shape=(4, 6, 9), dtype=int32, numpy=
array([[[99, 99, 99, 99, 99, 99, 99, 99, 99],
        [99, 99, 99, 99, 99, 99, 99, 99, 99],
        [99, 99, 99, 99, 99, 99, 99, 99, 99],
        [99, 99, 99, 99, 99, 99, 99, 99, 99],
        [99, 99, 99, 99, 99, 99, 99, 99, 99],
        [99, 99, 99, 99, 99, 99, 99, 99, 99]],

       [[99, 99, 99, 99, 99, 99, 99, 99, 99],
        [99, 99, 99, 99, 99, 99, 99, 99, 99],
        [99, 99, 99,  1,  3,  4, 99, 99, 99],
        [99, 99, 99,  3, 24,  5, 99, 99, 99],
        [99, 99, 99, 99, 99, 99, 99, 99, 99],
        [99, 99, 99, 99, 99, 99, 99, 99, 99]],

       [[99, 99, 99, 99, 99, 99, 99, 99, 99],
        [99, 99, 99, 99, 99, 99, 99, 99, 99],
        [99, 99, 99,  1,  3,  4, 99, 99, 99],
        [99, 99, 99,  3, 24,  5, 99, 99, 99],
        [99, 99, 99, 99, 99, 99, 99, 99, 99],
        [99, 99, 99, 99, 99, 99, 99, 99, 99]],

       [[99, 99, 99, 99, 99, 99, 99, 99, 99],
        [99, 99, 99, 99, 99, 99, 99, 99, 99],
        [99, 99, 99, 99, 

In [88]:
#gather= gather slices from params axis according to indics
a= tf.constant([0, 2,1,4,1,35,3,1])
print(tf.gather(a, [2,4,7]))
print(tf.gather(a, [1,0,7]))

print(tf.gather(a, tf.range(2,5)))


tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([2 0 1], shape=(3,), dtype=int32)
tf.Tensor([1 4 1], shape=(3,), dtype=int32)


In [87]:
params = tf.constant([[0,1,2,3],
                      [5,6,7,8],
                      [0,1,2,3],
                      [5,6,7,8]])
print(tf.gather(params,[1,3],axis=1))
print(tf.gather(params,[1,3],axis=0))


tf.Tensor(
[[1 3]
 [6 8]
 [1 3]
 [6 8]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[5 6 7 8]
 [5 6 7 8]], shape=(2, 4), dtype=int32)


In [98]:
#gather_nd = gather slices from params into a tensor with shape specified by indices
print(tf.gather_nd(params, indices=[[3],[0]]))
print(tf.gather_nd(params, indices=[[3,1],[0,0]]))

tf.Tensor(
[[5 6 7 8]
 [0 1 2 3]], shape=(2, 4), dtype=int32)
tf.Tensor([6 0], shape=(2,), dtype=int32)


## Ragged Tensors

In a tensor if we want have create tensor it must have same number of col in each row of matrix i.e. it must be rectangular matrix

tf.constant([[1,2,4],
            [0,3],
            [3,4,5],
            [0]])
This cannot be tensor because it is not rectangular Tensor. So, what if we have data that is not rectangular. 

For this we use racked


In [102]:
X = [[1,2,4],
    [0,3],
    [3,4,5],
    [0]]
tensor_ragged = tf.ragged.constant(X)
print(tensor_ragged)
print(tensor_ragged.shape)

<tf.RaggedTensor [[1, 2, 4], [0, 3], [3, 4, 5], [0]]>
(4, None)


In [110]:
# boolean_mask = Applies a boolean mask to data without flattening the mask dimensions
import tensorflow as tf

X = [[1, 2, 4], 
     [0, 3],
     [3, 4, 5],
     [0]]

# Create a ragged tensor
tensor_ragged = tf.ragged.constant(X)
print("Ragged Tensor:")
print(tensor_ragged)
print(tensor_ragged.shape)

# Mask should match the number of elements in each row of the ragged tensor
# Correcting the mask
mask = tf.ragged.constant([[True, False, False],  # First row: Keep first element
        [True, False],          # Second row: Keep first element
        [False, False, True],   # Third row: Keep last element
        [True]])                 # Fourth row: Keep first element

# Apply boolean mask
tensor_ragged_bool = tf.ragged.boolean_mask(data=tensor_ragged, mask=mask).to_list()

print("Masked Ragged Tensor:")
print(tensor_ragged_bool)


Ragged Tensor:
<tf.RaggedTensor [[1, 2, 4], [0, 3], [3, 4, 5], [0]]>
(4, None)
Masked Ragged Tensor:
[[1], [0], [5], [0]]


In [119]:
print(tf.RaggedTensor.from_row_lengths(values = [1,2,4,5,5,7,8,9,0], row_lengths=[3,5,1]))
print(tf.RaggedTensor.from_row_splits(values = [1,2,4,5,5,7,8,9,0], row_splits=[0,3,8,9]))
print(tf.RaggedTensor.from_row_starts(values = [1,2,4,5,5,7,8,9,0], row_starts=[0,3,8]))

<tf.RaggedTensor [[1, 2, 4], [5, 5, 7, 8, 9], [0]]>
<tf.RaggedTensor [[1, 2, 4], [5, 5, 7, 8, 9], [0]]>
<tf.RaggedTensor [[1, 2, 4], [5, 5, 7, 8, 9], [0]]>


In [120]:
A= tf.constant([[1,3],[3,5],[5,6]])
tf.RaggedTensor.from_tensor(A)

<tf.RaggedTensor [[1, 3],
 [3, 5],
 [5, 6]]>

## Sparse Tensors

To deal data contains many zeros and a more efficent way of treating and storing these kinds of data is by using sparse tensors

In [125]:
#tf.sparse.SpareTensor(indices, values, dense_shape)

tensor_sparse = tf.sparse.SparseTensor(indices=[[2,2],[3,3],[4,4]], values=[1,2,3], dense_shape=[5,6])
print(tensor_sparse)
print(tf.sparse.to_dense(tensor_sparse))

SparseTensor(indices=tf.Tensor(
[[2 2]
 [3 3]
 [4 4]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 3], shape=(3,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))
tf.Tensor(
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 3 0]], shape=(5, 6), dtype=int32)


## String Tensors

In [127]:
tensor_string = tf.constant(["hello", "world"])
print(tensor_string)
print(tf.strings.join(tensor_string, separator=" "))

tf.Tensor([b'hello' b'world'], shape=(2,), dtype=string)
tf.Tensor(b'hello world', shape=(), dtype=string)


## Variables

Inital value will be updated as we train our model. So, we need to use variables which can be updated as we do model training.  

tf.Variable(
    initial_value=None,
    trainable=None,
    validate_shape=True,
    caching_device=None,
    name=None,
    variable_def=None,
    dtype=None,
    import_scope=None,
    constraint=None,
    synchronization=tf.VariableSynchronization.AUTO,
    aggregation=tf.compat.v1.VariableAggregation.NONE,
    shape=None,
    experimental_enable_variable_lifting=True
)


In [134]:
x=tf.constant([1,2])
x_var=tf.Variable(x,name='var1')
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [135]:
print(x_var.assign_sub([2,3]))

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([-1, -1], dtype=int32)>


In [136]:
print(x_var.assign_add([1,1]))

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([0, 0], dtype=int32)>


In [139]:
with tf.device('GPU:0'):
    x_1=tf.constant([1,2])
print(x_1,x_1.device)
with tf.device('GPU:1'):
    x_2=tf.constant([1,2])
print(x_2,x_2.device)
with tf.device('CPU:0'):
    x_3=x_1+x_2
print(x_3,x_3.device)

tf.Tensor([1 2], shape=(2,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([1 2], shape=(2,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([2 4], shape=(2,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
